export const DEVS_PICK_TITLES = [
  "Scarface",
  "The Godfather",
  "The Godfather Part II",
  "Goodfellas",
  "The Departed",
  "The Usual Suspects",
  "The Irishman",
  "Boyz n the Hood",
  "Reservoir Dogs",
  "Donnie Brasco",
  "Snatch",
  "Legend",
  "Layer Cake",
  "The Gentlemen",
  "Gangster No. 1",
  "Lock, Stock and Two Smoking Barrels",
  "Carlito's Way",
  "American Gangster",
  "Training Day",
  "Menace II Society",
  "New Jack City",
  "A Bronx Tale",
  "Juice",
  "Gridlock'd",
  "Gang Related",
  "Bullet",
  "Kill Bill: Vol. 1",
  "Kill Bill: Vol. 2",
  "Once Upon a Time in Hollywood",
  "Gangs of New York",
  "Inception",
  "Django Unchained",
  "The Wolf of Wall Street",
  "Shutter Island",
  "Catch Me If You Can",
  "The Hateful Eight",
  "The Revenant",
  "Titanic",
  "Before the Flood",
  "Above the Rim",
  "Poetic Justice",
  "The Matrix",
  "The Matrix Reloaded",
  "The Matrix Revolutions",
  "Human Traffic",
  "Mean Machine",
  "The Football Factory",
  "The Business",
  "Rise of the Footsoldier",
  "RocknRolla",
  "Dead Man's Shoes",
  "This is England",
  "East Is East",
  "West Is West",
];
