import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import { toast } from "sonner";

import "./index.css";

import App from "./App";
import { WatchlistProvider } from "@/context/WatchlistContext";
import { NavigationProvider } from "@/context/NavigationContext";
import { TooltipProvider } from "./context/TooltipContext";
import { ModalManagerProvider } from "@/context/ModalContext";

// PWA: registers the service worker generated by vite-plugin-pwa
const updateSW = registerSW({
  immediate: true,

  onNeedRefresh() {
    toast.message("Update available", {
      description: "Refresh to load the latest version.",
      action: {
        label: "Update",
        onClick: () => updateSW(true),
      },
      cancel: {
        label: "Later",
        onClick: () => {},
      },
      duration: Infinity,
    });
  },

  onOfflineReady() {
    toast.success("All systems cached. Standing by.", { duration: 5000 });
  },
});

const rootEl = document.getElementById("root");
if (!rootEl) throw new Error('Missing root element: <div id="root"></div>');

createRoot(rootEl).render(
  <WatchlistProvider>
    <TooltipProvider>
      <NavigationProvider>
        <ModalManagerProvider>
          <App />
        </ModalManagerProvider>
      </NavigationProvider>
    </TooltipProvider>
  </WatchlistProvider>,
);
